### ISSUE TITLE
Modphred hanging

### ISSUE THREAD

**Issue by ulloaa** [novoalab/modPhred#10]
Hello, I run modphred with the test data in the tutorial as follows:
```
run -f ref/ECOLI.fa -o OUTPUT -i PRJEB22772/* -t4 \
-c dna_r10.3_450bps_fast.cfg \
--host /guppy/bin/guppy_basecall_server
```
However, even though the guppy_basecall_server is running, modphred seems to be expecting for a different output in the guppy log and just waits indefinitely. 

The guppy log indicates the basecall server is running as:
```
Starting server on port: ipc:///tmp/07f7-506f-964b-2342
```

So my question is whether modphred is expecting the basecall server to open a TCP port instead of the above?

Thanks!

**Comment by lpryszcz** [comment]
Hi @ulloaa, I guess you're using very recent guppy version, v6+, right? 
I (and others) have experienced [the same problem](https://github.com/nanoporetech/pyguppyclient/issues/13). 
But I was able to make pyguppyclient working stable with guppy up to version v5. The good news that all models from v6 works ok in v5.0.11 as well :) 
Could you try modPhred with guppy v5.0.11, please?

**Comment by ulloaa** [comment]
So I tried with guppy 5.0.11 and a few other versions but ran into the same error. I tried the container version for guppy 5.0.11 but it hung with the output:
```
[2022-12-28 11:05:34.275298] [0x00002aaab55e8700] [info]    Connecting to server as ''
[2022-12-28 11:05:34.296421] [0x00002aaab77e9700] [info]    Connecting to server as ''
[2022-12-28 11:05:34.316061] [0x00002aaab77e9700] [info]    Connecting to server as ''
[2022-12-28 11:05:34.335318] [0x00002aaab77e9700] [info]    Connecting to server as ''
```

However, the container version for 3.6.1 worked perfectly.

**Comment by neuropathbasel** [comment]
I have the same problem with guppy v6.x. I am trying to launch a guppy_basecall_server with respective option, e.g., `--port 5555`. A process starts, also with GPU support, but no TCP/IP ports opens as nmap tells me. When I try to connect to the server process with guppy_basecall_client, I get the (expected) message that it could not connect to the server. This holds true for both, running the server/client on a single machine (i.e. localhost:5555) or remotely (machine-IP:5555). A fix for this (guppy 6.x) is desperately needed.

**Comment by lpryszcz** [comment]
Hi, as I've mentioned before, only pyguppyclient developers could solve it, but it seems the project is already deprecated https://github.com/nanoporetech/pyguppyclient/issues/13

From my side, the only solution is to run basecalling with `--fast5_out` and later processing Fast5 files that are basecalled and with modification encoded using modPhred. This is suboptimal, but no other option exists at the moment I'm afraid.
