### ISSUE TITLE
clustering

### ISSUE THREAD

**Issue by emilmichgithub** [novoalab/modPhred#11]
Hi. Using a container, we have your program running with the provided test dataset-it's beautiful!. 

My question regards how to best get the clustering working. I have only been doing bioinformatics a year so I apologize for the naive question. How should I specify a short region to analyze the clustering on? Is it incorporated into the mod_cluster.py command? Or, is it specified in the reference genome and the corresponding index? Or some other way? 

thanks for the help.

**Comment by soniacruciani** [comment]
Hi Emilio, 
What I do is to subset the mod.gz file based on the coordinates of interest. 
The program is thought for clustering all the mods in mod.gz, so if you want to apply it to a certain subset of sites (i.e. that fall in the coordinates of a gene) you should subset the sites of mod.gz.
I wrote a very basic command for creating a mod.gz file with only the sites of interest (for chrN:start_coord-end_coord of your region of interest):

`zcat mod.gz | head -n 17 > subset_mod
 zgrep chrN mod.gz | awk '{if ($2>=here_write_start_coord && $2<=here_write_end_coord) print $0}' >> subset_mod
gzip subset_mod`

Just run this and provide the new mod.gz file as input for the clustering.
I know it is not ideal but if you have multiple regions you can loop it over their coordinates assigning a variable to chr, start and end coordinates. Hope this helps! 
Cheers, 

Sonia

**Comment by lpryszcz** [comment]
Hi, it's not mentioned in docs, but you can specify regions of interest using `-r`, for example if you want to cluster reads that aligned to chr1 at positions between 100 and 200 on the + strand, you'd run it as follows: 

```bash
~/src/modPhred/src/mod_cluster.py --minfreq 0.01 -i mod.gz -e pdf -r chr1:100-200+
```

Note, you can provide multiple regions separated by spaces. 

Added this to docs.
