### ISSUE TITLE
KeyError: 'MaxPhredProb' in mods_from_bams.py script

### ISSUE THREAD

**Issue by NuriaDiaz** [novoalab/modPhred#12]
Dear developers,
I'm trying to run the mods_from_bams.py script.
I run the following command:
`(modPhred) diaz@Uwe2:/media/data/nuria/bcn_nanopore/files$ ~/src/modPhred/src/mods_from_bams.py -i sample1.bam sample2.bam -f GRCm39.genome.fa -o ./sample1_vs_sample2`

In the "modPhred" conda environment I've all the dependencies described in your documentation.

However I get the following error:
```
[2023-08-01 17:47:04] ===== Welcome, welcome to modPhred pipeline! =====
Traceback (most recent call last):
  File "/home/diaz/src/modPhred/src/mods_from_bams.py", line 86, in <module>
    main()
  File "/home/diaz/src/modPhred/src/mods_from_bams.py", line 59, in main
    MaxPhredProb = data["MaxPhredProb"]
KeyError: 'MaxPhredProb'
```

Could you be so kind to give me a hint to run the code?
Thanks in advance and best regards,
Núria

**Comment by ana-mil** [comment]
Hello Nuria,

**Comment by ana-mil** [comment]
Hello Nuria,
[modPhred.zip](https://github.com/novoalab/modPhred/files/12260015/modPhred.zip)

Could you please provide the full paths for all of the files you are using in your command, for me to check? Also, what you will need is the modPhred.pkl file, which I am guessing you do not have (I have attached it, zipped, here), in the same folder as where you have the subfolder with all your bam files. So you'd have modPhred.pkl file and my_bams/ folder in the same folder, e.g. my_folder/. And then the you pass the input bam files via "-i /path/to/my_folder/my_bams/*.bam" (in this scenario, you'd have the .pkl file as: /path/to/my_folder/modPhred.pkl, this is where modPhred expects it to be). 

I hope this helps.

Best regards,

Ana

**Comment by NuriaDiaz** [comment]
Hi Ana,

Thanks a lot for your reply, I've provided full paths, I was executing modPhred from the folder where I have the bams stored.

I'll save the modPhred.pkl file as you indicate and the bams as well and execute it again.

Best wishes,
Núria ^^

**Comment by NuriaDiaz** [comment]
Unfortunatelly, still getting the same error. Here you can see now the folder contents and full paths:

```
(modPhred) diaz@Uwe2:/media/data/nuria/bcn_nanopore/files/bams_modPhred$ ls
sample1.bam  sample2.bam
(modPhred) diaz@Uwe2:/media/data/nuria/bcn_nanopore/files$ ls
modPhred.pkl
modPhred.zip

(modPhred) diaz@Uwe2:~$ ~/src/modPhred/src/mods_from_bams.py -i /media/data/nuria/bcn_nanopore/files/bams_modPhred/*bam -f /media/data/nuria/bcn_nanopore/files/GRCm39.genome.fa -t 24 -o /media/data/nuria/bcn_nanopore/files/sample1_vs_sample2
[2023-08-04 13:22:15] ===== Welcome, welcome to modPhred pipeline! =====
Traceback (most recent call last):
  File "/home/diaz/src/modPhred/src/mods_from_bams.py", line 86, in <module>
    main()
  File "/home/diaz/src/modPhred/src/mods_from_bams.py", line 59, in main
    MaxPhredProb = data["MaxPhredProb"]
KeyError: 'MaxPhredProb'

```
Thanks a lot for your help beforehand :)
Núria

**Comment by ana-mil** [comment]
Another thing, the existing mod.gz file in this folder, even if empty, needs to be deleted before running the command. And I the output folder (-o) needs to exist.

Cheers,

Ana

**Comment by NuriaDiaz** [comment]
Thanks for the feedback, folder exists and there isn't any mod.gz file in the folder (neither in the output one, nor in the one containing the modPhred.pkl, still getting the same error :(

**Comment by ana-mil** [comment]
Just to confirm, the bams are the ones that we have produced here and passed to you?

**Comment by NuriaDiaz** [comment]
Yes, they are

**Comment by soniacruciani** [comment]
Hello, have you finally solved this? 
Apologies for the non-informative error message. I think the problem was that the `modPhred.pkl` file has to be in the output folder, so if you have modPhred.pkl in `/media/data/nuria/bcn_nanopore/files` then you have to run the command with `-o /media/data/nuria/bcn_nanopore/files`.

**Comment by NuriaDiaz** [comment]
Hi,

I’ve also tried running it with the modPhred.pkl in the output folder after I visited the lab in summer. That also didn’t work.
I’m currently on sick leave, will be back at some point in February-March in the lab.
Will get back to you as soon as I’m back to work again.

Thanks a lot for your e-mail and have a good festive season.

Best wishes,

Núria Díaz i Pedrosa
Institute of Experimental Cardiology | Heidelberg University Hospital
Im Neuenheimer Feld 669
69120 Heidelberg, Deutschland

Tel. +49-6221-56-32183
E: ***@***.******@***.***>
E: ***@***.******@***.***>

**Comment by enovoa** [comment]
hi @NuriaDiaz - have you solved this? In the meantime we are planning to embed modPhred into MasterOfpores NextFlow workflow, to ensure that there are no errors caused by the use of different software versions/dependencies. We hope to have this set up in a couple of weeks and will update the README accordingly. Thanks!
