### ISSUE TITLE
modphred and RNA004

### ISSUE THREAD

**Issue by mocherry** [novoalab/modPhred#14]
Dear all,

will modphred work with RNA004-data basecalled with Dorado to detect RNA m6A?

Thanks and best
Matthias

**Comment by lpryszcz** [comment]
Hi, no, it only supports modifications encoded in Fast5 (guppy modification-aware flip-flop models).

**Comment by enovoa** [comment]
Adding this information to the README - as now ModPhred will become deprecated as it relies on Guppy basecalling which has itself become deprecated (ONT has switched to support Dorado).
