### ISSUE TITLE
package required for mod_cluster.py not included in the image

### ISSUE THREAD

**Issue by soniacruciani** [novoalab/modPhred#5]
Even though I used the singularity image I got this error when running mod_cluster.py:

Traceback (most recent call last):
  File "/users/enovoa/scruciani/soft/modPhred/src/mod_cluster.py", line 21, in <module>
    from sklearn.decomposition import PCA
ModuleNotFoundError: No module named 'sklearn'

--> should add scikit-learn to the image?

**Comment by lpryszcz** [comment]
indeed, sklearn was missing. updated requirements and docker images. 
thanks!
