### ISSUE TITLE
how to specify input for read_cluster.py?

### ISSUE THREAD

**Issue by soniacruciani** [novoalab/modPhred#7]
Hello, 
I want to run read clustering on different samples separately (2 CTR and 2 KO), which were originally processed together so I have a common mod.gz for the 4 samples.
I tried to input a "subset" mod.gz with only the columns for CTR samples but the output still contains the reads from the KO samples... how can I specify what input samples  I want to run the clustering on?

**Comment by lpryszcz** [comment]
is it still pending?

**Comment by soniacruciani** [comment]
the mods_from_bam.py was a good workaround :)
