### ISSUE TITLE
Unable to find executables/scripts after conda installation

### ISSUE THREAD

**Issue by bastian-wur** [novoalab/modPhred#8]
Hi everyone,

I just installed modPhred via conda, and would now like to run the test data.
I would expect that I have the relevant scripts like modEncode or modAlign in the path... but I do not. 
So... how do I run them/where are they?

Thanks,
Bastian

**Comment by enovoa** [comment]
Hi, have you followed these instructions? https://modphred.readthedocs.io/en/latest/install.html

**Comment by bastian-wur** [comment]
Okay, now I'm embarrassed, because this was indeed a case of RTFM.
I only followed the conda instructions, thinking you'd have modphred already in conda, and then forgot to actually clone the git repository.
I'm sorry.
